//
// Created by Marcelo on 4/30/2023.
//

#ifndef FINALPROJECT_SOUNDS_H
#define FINALPROJECT_SOUNDS_H

enum Sounds {
    CLICK1, CLICK2, DROP1, DROP2, DROP3, FAILED1, FAILED2, FAILED3, FAILED4,
    GRAB1, GRAB2, GRAB3, GRAZE_ON_THE_ROOF, RIGHT1, RIGHT2, RIGHT3, RIGHT4,
    SPECIAL_DROP, SPECIAL_GRAB, YEA_BABY
};

#endif //FINALPROJECT_SOUNDS_H
